### ISSUE TITLE
Fix. Mediainfo & genss module.  It doesn't work 

### ISSUE THREAD

**Issue by shado-hackers** [yasirarism/MissKatyPyro#295]
In. Mediainfo it gives this problem 
![Uploading Screenshot_2024-05-14-08-05-59-37_948cd9899890cbd5c2798760b2b95377.jpg…]()

**app/misskaty/helper/localization.py", line 102, in wrapper
2024-05-14T02:29:14.429853+00:00 app[worker.1]:     return await func(client, message, lfunc)
2024-05-14T02:29:14.429854+00:00 app[worker.1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-14T02:29:14.429854+00:00 app[worker.1]:   File "/app/misskaty/plugins/mediainfo.py", line 54, in mediainfo
2024-05-14T02:29:14.429854+00:00 app[worker.1]:     output_ = await runcmd(f'mediainfo "{file_path}"')
2024-05-14T02:29:14.429854+00:00 app[worker.1]:               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-14T02:29:14.429854+00:00 app[worker.1]:   File "/app/misskaty/helper/media_helper.py", line 59, in runcmd
2024-05-14T02:29:14.429855+00:00 app[worker.1]:     process = await asyncio.create_subprocess_exec(
2024-05-14T02:29:14.429855+00:00 app[worker.1]:               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-14T02:29:14.429855+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.12/asyncio/subprocess.py", line 224, in create_subprocess_exec
2024-05-14T02:29:14.429855+00:00 app[worker.1]:     transport, protocol = await loop.subprocess_exec(
2024-05-14T02:29:14.429855+00:00 app[worker.1]:                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-14T02:29:14.429856+00:00 app[worker.1]:   File "uvloop/loop.pyx", line 2820, in subprocess_exec
2024-05-14T02:29:14.429856+00:00 app[worker.1]:   File "uvloop/loop.pyx", line 2778, in __subprocess_run
2024-05-14T02:29:14.429856+00:00 app[worker.1]:   File "uvloop/handles/process.pyx", line 611, in uvloop.loop.UVProcessTransport.new
2024-05-14T02:29:14.429856+00:00 app[worker.1]:   File "uvloop/handles/process.pyx", line 112, in uvloop.loop.UVProcess._init
2024-05-14T02:29:14.429856+00:00 app[worker.1]: FileNotFoundError: [Errno 2] No such file or directory**
 

In genss. Got this problem 

**Failed screenshoot generation.

'NoneType' object has no attribute 'name'**

**Comment by yasirarism** [comment]
Use python 3.11 or build using docker, for python 3.12 need many changes in library

**Comment by yasirarism** [comment]
I'm already update to python 3.12 and nothing find any issue. So this case closed, it's because your fault.
